[build]
  command = "npm run netlify-build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Redirects for Next.js
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle file uploads
[[redirects]]
  from = "/uploads/*"
  to = "/api/upload"
  status = 200

# Handle all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
